language: rust
sudo: false
rust:
  - nightly

cache: cargo

env: RUST_BACKTRACE=1

script:
- rustup target add wasm32-unknown-unknown
- cd jbaublitz-me-wasm
- wasm-pack build --target no-modules
- cd ..
- cp contact.css humans.css index.css index.html template.css jbaublitz-me-wasm/pkg
after_success:
- cd ./jbaublitz-me-wasm/pkg
- ls
- git init
- git checkout -b gh-pages
- git add -A .
- git status
- git -c user.name='travis' -c user.email='travis' commit -m "Travis auto-deploy"
- git push -f https://jbaublitz:$GITHUB_TOKEN@github.com/jbaublitz/jbaublitz-me-gh-pages gh-pages
