language: rust
sudo: false

cache: cargo

script:
  # Builds on nightly.
  - rust: nightly
    env: RUST_BACKTRACE=1
    before_script:
      - rustup target add wasm32-unknown-unknown
    script:
      - cd jbaublitz-me-wasm
      - cargo install wasm-pack
      - wasm-pack build --no-modules

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
